### ISSUE TITLE
BMKG to PHA: consider events not having phase data

### ISSUE THREAD

**Issue by yudhastyawan** [comp-geoph-itera/Lindu-HypoDD#1]
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/39240883/204691718-2281f446-d5a2-46ad-b1cf-2c2bbbc73e31.png">

This is an example of the event not having phase data. Errors in the terminal would be like the outcomes below:
```
Traceback (most recent call last):
  File ".../convertBMKGtoPHA.py", line 112, in <module>
    main.write(filename)
  File ".../convertBMKGtoPHA.py", line 91, in write
    pha_list.append("# " + " ".join([str(e[key][i]) for key in list(e.keys())]))
  File ".../convertBMKGtoPHA.py", line 91, in <listcomp>
    pha_list.append("# " + " ".join([str(e[key][i]) for key in list(e.keys())]))
IndexError: list index out of range
```

**Comment by yudhastyawan** [comment]
```python
....
def __init__(self, filename):
        ....
        self.bug_events = {key:[] for key in ['ID']}
        ....
    
    def read(self):
        ....
        with open(self.filename, 'r') as file:
            for item in file:
                currLine = item.split()
                if ev == True:
                    ....
                    
                    # for bug purposes only
                    self.bug_events["ID"].append(item)

                    ....
....
```

Storing each "item" would be good enough for detecting this problem.
